### ISSUE TITLE
[URL]

### ISSUE THREAD

**Issue by stysan** [Discord-AntiScam/scam-links#60]
**URL**
discrod.com
dlscord.com

**Additional context**
discrod.com
Asks about your age and your gender (male/female).
![Screenshot 2022-09-20 at 14-59-06 Ваш пол и возраст](https://user-images.githubusercontent.com/55314369/191251850-bd1fc4d3-17e7-4d5a-8f96-6c85627bfd85.png)  

dlscord.com
Sending me to an Instagram page.

**Comment by actually-akac** [comment]
Hi @stysan, thank you for bringing this to our attention.

> `discrod.com`

We've never added this domain into the database. I will be ignoring this.

> `dlscord.com`

While this domain is currently used for a different purpose, it used to host a confirmed phishing content on it in the past. We will not remove domains from the database, even if they're repurposed or taken down. Since there's always a possibility of it coming back to harm users, we've decided to keep this in the database. Additionally, it's useful for conducting research as you have tons of data to work with.

URL: `https://dlscord.com/appinfo`

Context:
```
This gift is for you bro!
Nitro free from steam!
https://dlscord.com/appinfo
```
